### ISSUE TITLE
build on PG 10.3

### ISSUE THREAD

**Issue by csawyerYumaed** [marcmunro/veil#2]
``
src/veil_shmem.c: In function '_PG_init':
src/veil_shmem.c:125:2: warning: implicit declaration of function 'RequestAddinLWLocks' [-Wimplicit-function-declaration]
  RequestAddinLWLocks(veil_dbs);
  ^~~~~~~~~~~~~~~~~~~

src/veil_shmem.c: In function 'shmalloc_init':
src/veil_shmem.c:452:18: warning: implicit declaration of function 'LWLockAssign' [-Wimplicit-function-declaration]
     VeilLWLock = LWLockAssign();
                         ^~~~~~~~~~~~
src/veil_shmem.c:452:16: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
     VeilLWLock = LWLockAssign();
                         ^
``

but it does build.  Except when running make check:
``
ERROR:  could not load library "/usr/local/pgsql/lib/veil.so": /usr/local/pgsql/lib/veil.so: undefined symbol: LWLockAssign
``
So clearly the build didn't go very well.

Also I had to change strip_version() in find_pg_config to:
``
sed 's/PostgreSQL //'
``
to get it to build as well as it did here.

**Comment by marcmunro** [comment]
On Wed, 2018-05-02 at 10:15 -0700, csawyerYumaed wrote:
> ``
> src/veil_shmem.c: In function '_PG_init':
> src/veil_shmem.c:125:2: warning: implicit declaration of function
> 'RequestAddinLWLocks' [-Wimplicit-function-declaration]
> RequestAddinLWLocks(veil_dbs);
> ^~~~~~~~~~~~~~~~~~~
> src/veil_shmem.c: In function 'shmalloc_init':
> src/veil_shmem.c:452:18: warning: implicit declaration of function
> 'LWLockAssign' [-Wimplicit-function-declaration]
> VeilLWLock = LWLockAssign();
> ^~~~~~~~~~~~
> src/veil_shmem.c:452:16: warning: assignment makes pointer from
> integer without a cast [-Wint-conversion]
> VeilLWLock = LWLockAssign();
> ^
> ``
> but it does build. Except when running make check:
> ERROR: could not load library "/usr/local/pgsql/lib/veil.so":
> /usr/local/pgsql/lib/veil.so: undefined symbol: LWLockAssign
> So clearly the build didn't go very well.
> Also I had to change strip_version() in find_pg_config to:
> sed 's/PostgreSQL //'
> to get it to build as well as it did here.

I will take a look in the next few days.  

Good to know that someone is interested.  Thanks for the report.


__
Marc

**Comment by marcmunro** [comment]
On Thu, 2018-05-03 at 18:34 -0700, Marc Munro wrote:
> I will take a look in the next few days.  
> 
> Good to know that someone is interested.  Thanks for the report.
> 
Version 10.3 of veil has been released.  This seems to fix the reported
issues.  All tests have been run and have passed.

__
Marc
